version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - zip function.zip lambda_function.py
artifacts:
  files:
    - function.zip
post_build:
  commands:
    - echo "Updating lambda Function..."
    - aws lambda update-function-code --function-name TodoAPIHandler --zip-file fileb://function.zip
    - echo "DONE!!"
